language: java
jdk:
  - oraclejdk8
#Activate container based infra https://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
env:
  - MAVEN_OPTS="-Xmx3000m"
install: mvn clean -V
script: mvn test -V -Ptravisci