# This is a basic workflow to help you get started with Using Checkmarx CxFlow Action


name: CxFlow

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel - this job is specifically configured to use the Checkmarx CxFlow Action
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on - Ubuntu is required as Docker is leveraged for the action
    runs-on: ubuntu-latest

    # Steps require - checkout code, run CxFlow Action, Upload SARIF report (optional)
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - id: get-branch
      run: |
        branch=$(echo ${{ github.ref }} | cut -d/ -f3)
        echo "::set-output name=branch::$branch"
    # Runs the Checkmarx Scan leveraging the latest version of CxFlow - REFER to Action README for list of inputs
    - name: Checkmarx CxFlow Action
      #env:
        #JAVA_TOOL_OPTIONS: '-Dhttps.proxyHost=1.1.1.1 -Dhttps.proxyPort=1234'
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1
      with:
        project: GitHub-find-sec-bugs-${{ steps.get-branch.outputs.branch }}
        team: '/CxServer/SP/ANZ/CBA-GH-POC'
        checkmarx_url: ${{ secrets.CHECKMARX_URL }}
        checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}
        checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
        checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
        github_token: ${{ secrets.GH_TOKEN }}
        incremental: false
        break_build: false
        scanners: sast
        bug_tracker: Sarif
        #comment-script: ..\CxComment.groovy
        #params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }} --http-read-timeout=600000 --severity="High" --severity="Medium" --severity="Low" --severity="Informational"
        params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }} --http-read-timeout=600000 --cx-flow.comment-script="./CxComment.groovy"
    # Upload the Report for CodeQL/Security Alerts
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: cx.sarif
